all:
	go build -o raftexample main.go
	mkdir -p ./instance1/log; cp raftexample ./instance1
	mkdir -p ./instance2/log; cp raftexample ./instance2
	mkdir -p ./instance3/log; cp raftexample ./instance3
